### ISSUE TITLE
Unknown model iris_UST10LX

### ISSUE THREAD

**Issue by shenqg168** [shenmuxin/uav_tracking_metaRL#2]
Muxin, hello.
I encountered the following error while reproducing your code:
I have followed the installation steps as follows: Copy the robotic model located in the /models directory of this project to the /PX4-Autopilot/Tools/sitl_gazebo/models directory.
There was an issue encountered while executing roslaunch uav_tracking_metaRL setup_2uavs.launch.
**Error: Unknown model iris_UST10LX**
 Can you please tell me how to solve it.Looking forward to your reply！

**Comment by shenmuxin** [comment]
About this issue, you can follow the [(3.2 Modification in PX4)](https://github.com/shenmuxin/uav_tracking_metaRL#32-modification-in-px4) in the `Readme.md`. 

Specifically speaking, you should add the two custom models in the path `/models` to the storage path of PX4, which are ` imu_gazebo` and `iris_UST10LX`. After doing this, you should modify some files in PX4 and recompile, so that PX4 can find the custom models. To avoid redundancy, I've omitted the details of adding a custom model. You can follow this [answer](https://discuss.px4.io/t/create-custom-model-for-sitl/6700) carefully.

Hope this can be helpful.

![1710127727386](https://github.com/shenmuxin/uav_tracking_metaRL/assets/87429023/a5717985-28ba-49d0-9e02-6a59d651650e)

**Comment by shenqg168** [comment]
Thank you very much! The model issue has been resolved, but a new problem has emerged. When running rosrun uav_tracking_metaRL pearl_trainer_node.py in the Conda virtual environment, the following error occurs:
`*****************************************
	[finish test]

Collecting initial pool of data for train and eval
  0%|                                                                               | 0/3 [00:00<?, ?it/s]Current task index is 0 vx:0.6 yaw_rate:-0.04
[INFO] [1710222725.325295, 291.358000]: ==================================
[INFO] [1710222725.328393, 291.362000]: >>>>>> Generate Cylinders >>>>>>
[INFO] [1710222744.859576, 310.864000]: Begin Game
Current task index is 0 vx:0.6 yaw_rate:-0.04
  0%|                                                                               | 0/3 [00:48<?, ?it/s]
Traceback (most recent call last):
  File "/home/sj/shen_ws/rl_drone/catkin_ws/devel/lib/uav_tracking_metarl/pearl_trainer_node.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/sj/shen_ws/rl_drone/catkin_ws/src/uav_tracking_metarl/scripts/pearl2buf/pearl_trainer_node.py", line 91, in <module>
    meta_learner.meta_train()
  File "/home/sj/shen_ws/rl_drone/catkin_ws/src/uav_tracking_metarl/scripts/pearl2buf/algorithm/meta_learner.py", line 225, in meta_train
    self.collect_train_data(
  File "/home/sj/shen_ws/rl_drone/catkin_ws/src/uav_tracking_metarl/scripts/pearl2buf/algorithm/meta_learner.py", line 194, in collect_train_data
    trajs, num_samples = self.sampler.obtain_samples(
  File "/home/sj/shen_ws/rl_drone/catkin_ws/src/uav_tracking_metarl/scripts/pearl2buf/algorithm/sampler.py", line 46, in obtain_samples
    traj = self.rollout(task_index=task_index, accum_context=accum_context)
  File "/home/sj/shen_ws/rl_drone/catkin_ws/src/uav_tracking_metarl/scripts/pearl2buf/algorithm/sampler.py", line 76, in rollout
    action = self.agent.get_action(obs)
  File "/home/sj/shen_ws/rl_drone/catkin_ws/src/uav_tracking_metarl/scripts/pearl2buf/algorithm/sac.py", line 97, in get_action
    action, _ = self.policy(inputs)
  File "/home/sj/anaconda3/envs/env_meta/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sj/shen_ws/rl_drone/catkin_ws/src/uav_tracking_metarl/scripts/pearl2buf/algorithm/networks.py", line 193, in forward
    x = self.hidden_activation(fc_layer(x))
  File "/home/sj/anaconda3/envs/env_meta/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sj/anaconda3/envs/env_meta/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x17 and 52x300)
`
Sometimes when starting PX4 and Gazebo, the following error may be prompted:
ERROR [simulator] poll timeout 0, 22
ERROR [simulator] poll timeout 0, 22
ERROR [simulator] poll timeout 0, 22
ERROR [simulator] poll timeout 0, 22
ERROR [simulator] poll timeout 0, 22
Can you please tell me how to solve it? Looking forward to your reply！

**Comment by shenmuxin** [comment]
`File "/home/sj/shen_ws/rl_drone/catkin_ws/src/uav_tracking_metarl/scripts/pearl2buf/algorithm/networks.py", line 193, in forward
x = self.hidden_activation(fc_layer(x))
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x17 and 52x300)`

Maybe the dimension of the nueral network is incorrect. The dimension of the state is 47, and the dimension of the action is 2. You should check it out carefully.

**Comment by darlingbenke** [comment]
I couldn't find the paper. Could you provide it

**Comment by NabeelEhsan** [comment]
Hi @shenqg168 @darlingbenke @shenmuxin 
I hope you're doing well. I noticed that you had previously reported a similar error in the uav_tracking_metarl repo involving:

user@ubuntu:~$ rosrun uav_tracking_metaRL pearl_trainer_node.py

*****************************************
	[test libraries]:

 - rospy.__file__ = /opt/ros/noetic/lib/python3/dist-packages/rospy/__init__.py
- tensorboardX.__file__ = /home/user/.local/lib/python3.8/site-packages/tensorboardX/__init__.py
 - SAC.__file__ = /home/user/your_workspace_name/src/uav_tracking_metaRL/scripts/pearl/algorithm/sac.py

*****************************************
	[finish test]

Collecting initial pool of data for train and eval
  0%|                                                                     | 0/3 [00:00<?, ?it/s]Current task index is 0 vx:0.6 yaw_rate:-0.04
[INFO] [1745241981.817979, 191.592000]: ==================================
[INFO] [1745241981.820609, 191.593000]: >>>>>> Generate Cylinders >>>>>>
[ERROR] [1745242116.025032, 270.098000]: failed to send mode command
[ERROR] [1745242117.540549, 271.101000]: failed to send mode command
[ERROR] [1745242119.567455, 272.099000]: failed to send mode command
[ERROR] [1745242121.119220, 273.099000]: failed to send mode command
[ERROR] [1745242123.134957, 274.100000]: failed to send mode command
[ERROR] [1745242130.138249, 277.961000]: iris_UST10LX failed to send arm command
[ERROR] [1745242135.145841, 280.575000]: iris_UST10LX failed to send arm command
[ERROR] [1745242140.156689, 283.466000]: iris_UST10LX failed to send arm command
[ERROR] [1745242145.164684, 286.441000]: iris_UST10LX failed to send arm command
[ERROR] [1745242150.172103, 289.194000]: iris_UST10LX failed to send arm command
[ERROR] [1745242155.178605, 292.130000]: iris_UST10LX failed to send arm command
[ERROR] [1745242160.187129, 294.698000]: iris_UST10LX failed to send arm command
[ERROR] [1745242165.199202, 297.430000]: iris_UST10LX failed to send arm command
[ERROR] [1745242170.213732, 300.133000]: iris_UST10LX failed to send arm command
[ERROR] [1745242175.221224, 303.214000]: iris_UST10LX failed to send arm command
[INFO] [1745242203.601477, 319.215000]: Begin Game
Current task index is 0 vx:0.6 yaw_rate:-0.04
  0%|                                                                     | 0/3 [05:28<?, ?it/s]
Traceback (most recent call last):
  File "/home/user/your_workspace_name/devel/lib/uav_tracking_metaRL/pearl_trainer_node.py", line 15, in <module>
    exec(compile(fh.read(), python_script, 'exec'), context)
  File "/home/user/your_workspace_name/src/uav_tracking_metaRL/scripts/pearl/pearl_trainer_node.py", line 92, in <module>
    meta_learner.meta_train()
  File "/home/user/your_workspace_name/src/uav_tracking_metaRL/scripts/pearl/algorithm/meta_learner.py", line 225, in meta_train
    self.collect_train_data(
  File "/home/user/your_workspace_name/src/uav_tracking_metaRL/scripts/pearl/algorithm/meta_learner.py", line 194, in collect_train_data
    trajs, num_samples = self.sampler.obtain_samples(
  File "/home/user/your_workspace_name/src/uav_tracking_metaRL/scripts/pearl/algorithm/sampler.py", line 46, in obtain_samples
    traj = self.rollout(task_index=task_index, accum_context=accum_context)
  File "/home/user/your_workspace_name/src/uav_tracking_metaRL/scripts/pearl/algorithm/sampler.py", line 76, in rollout
    action = self.agent.get_action(obs)
  File "/home/user/your_workspace_name/src/uav_tracking_metaRL/scripts/pearl/algorithm/sac.py", line 97, in get_action
    action, _ = self.policy(inputs)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/your_workspace_name/src/uav_tracking_metaRL/scripts/pearl/algorithm/networks.py", line 193, in forward
    x = self.hidden_activation(fc_layer(x))
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.local/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x17 and 52x300)
user@ubuntu:~$ 



I wanted to ask if you were able to resolve this, and if so, could you share any tips or adjustments you made—particularly regarding the input/output dimensions for the neural network?

I’d really appreciate any insights. Thanks again!

Best regards,
Nabeel
